config/routes.rb
Rails.application.routes.draw do
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'people#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
    validates :first_name, presence: true
    validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
    before_action :set_person, only: [:show, :edit, :update, :destroy]

    # GET /people
    # GET /people.json
    def index
        @people = Person.all
        # added:
        @person = Person.new
    end

    # GET /people/1
    # GET /people/1.json
    def show; end

    # GET /people/new
    def new
        @person = Person.new
    end

    # GET /people/1/edit
    def edit; end

    # POST /people
    # POST /people.json
    def create
        @person = Person.new(person_params)

        respond_to do |format|
            if @person.save
                format.html { redirect_to @person, notice: 'Person was successfully created.' }
                format.json { render :show, status: :created, location: @person }
                # added:
                format.js   { render :show, status: :created, location: @person }
            else
                format.html { render :new }
                format.json { render json: @person.errors, status: :unprocessable_entity }
                # added:
                format.js   { render json: @person.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /people/1
    # PATCH/PUT /people/1.json
    def update
        respond_to do |format|
            if @person.update(person_params)
                format.html { redirect_to @person, notice: 'Person was successfully updated.' }
                format.json { render :show, status: :ok, location: @person }
            else
                format.html { render :edit }
                format.json { render json: @person.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /people/1
    # DELETE /people/1.json
    def destroy
        @person.destroy
        respond_to do |format|
            format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_person
        @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
        params.require(:person).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Rails4 Ajax Render</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]> <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script> <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script> <![endif]-->

    </head>

    <body>
        <%= yield %>
    </body>
</html>

app/views/people/_form.html.erb
<%# Conditionally set remote: true. Also, passing model name as data attribute %>
<% modal ||= false %>
<% remote = modal ? true : false %>
<%= form_for(@person, remote: remote, html: {role: :form, 'data-model' => 'person'}) do |f| %>

<% if @person.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(@person.errors.count, "error") %>
        prohibited this person from being saved:</h2>

    <ul>
        <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>

<%# Added Bootstrap classes, and help-block container for error messages %>
<div class="form-group">
    <%= f.label :first_name, class: 'control-label' %><br>
    <%= f.text_field :first_name, class: 'form-control' %>
    <span class="help-block"></span>
</div>

<%# Added Bootstrap classes, and help-block container for error messages %>
<div class="form-group">
    <%= f.label :last_name, class: 'control-label' %><br>
    <%= f.text_field :last_name, class: 'form-control' %>
    <span class="help-block"></span>
</div>

<%# Added Bootstrap classes %>
<div class="actions">
    <%= f.submit 'Submit', class: 'btn btn-default' %>
</div>

<% end %>

app/views/people/_table_row.html.erb
<tr>
    <td><%= person.first_name %></td>
    <td><%= person.last_name %></td>
    <td><%= link_to 'Show', person %></td>
    <td><%= link_to 'Edit', edit_person_path(person) %></td>
    <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody id="people_table">
    <% @people.each do |person| %>

        <%# Render table row partial for each person object %>
       <%= render partial: 'table_row', locals: {person: person} %>

    <% end %>
  </tbody>
</table>

<br>


<%# Added Bootstrap data modal attribute %>
<%= link_to 'New Person', '#new_person_modal', 'data-toggle' => 'modal' %>

<%# Bootstrap modal markup. @see: http://getbootstrap.com/javascript/#modals %>
<div class="modal fade" id="new_person_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Create new person</h4>
      </div>
      <div class="modal-body">
        <%# Render the new person form (passing modal => true to enable remote => true) %>
        <%= render 'form', modal: true %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @person.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @person.last_name %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/people/show.js.erb
$('#people_table').append("<%= j render partial: 'table_row', locals: {person: @person } %>");
$('#new_person_modal').modal_success();